⬆️ Bump attrs from 21.2.0 to 21.4.0 (#106)
* :arrow_up: Bump attrs from 21.2.0 to 21.4.0

Bumps [attrs](https://github.com/python-attrs/attrs) from 21.2.0 to 21.4.0.
- [Release notes](https://github.com/python-attrs/attrs/releases)
- [Changelog](https://github.com/python-attrs/attrs/blob/main/CHANGELOG.rst)
- [Commits](https://github.com/python-attrs/attrs/compare/21.2.0...21.4.0)

---
updated-dependencies:
- dependency-name: attrs
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* replacement to modern attrs

import attr ➡ import attrs
attr.s ➡ attrs.define
attr.ib ➡attrs.field
attr.validators➡attrs.validators

* fix long line

* use `slots=False` for attrs.define base classes

This fixes
> TypeError: multiple bases have instance lay-out conflict
See
https://www.attrs.org/en/stable/glossary.html#term-slotted-classes

See also https://github.com/python-attrs/attrs/issues/880

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: konstantin <konstantin.klein@hochfrequenz.de>