📦🐛use python 3.10 in package publishing workflow
The python publish workflow runs the type check in python 3.9 which doesn't work with the changes from #194.

The easiest fix is to run the checks before publishing in 3.10.

https://github.com/Hochfrequenz/ahbicht/actions/runs/2596809649

> type_check run-test: commands[0] | mypy --show-error-codes src/ahbicht
src/ahbicht/condition_node_builder.py:101: error: "AttributeError" has no attribute "name"  [attr-defined]
Found 1 error in 1 file (checked 37 source files)